apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bxsd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0034-tenant/tkrw-pr714-0075-0034-app/devfile-sample-bxsd@sha256:52bd475da9e8fb6fb5fe9ec2df0d7519e2ba6ac380241194e1918054c3bf2d34
        name: my-nodejs
        resources: {}
status: {}
